import { appendLog, hashPrompt } from "../log.js";
import { loadPolicy } from "../policy.js";

interface HookInput {
  session_id?: string;
  prompt?: string;
  user_prompt?: string;
  user_prompt_raw?: string;
}

const SYSTEM_TRAFFIC_MARKERS = [
  "[SYSTEM NOTIFICATION",
  "<task-notification>",
  "<system-reminder>",
  "<command-name>",
  "<local-command-stdout>",
  "Caveat: The messages below were generated by the user while running local commands",
];

export function isSystemTraffic(prompt: string): boolean {
  const head = prompt.slice(0, 2000);
  return SYSTEM_TRAFFIC_MARKERS.some((m) => head.includes(m));
}

// Classification moved into the session: the model runs `metaskill find` under
// the standing protocol injected at SessionStart. This hook now only records
// that a prompt happened, which is what the follow-through metric is measured
// against. It never writes to stdout, so it can never disturb the prompt.
export async function routeCommand(stdinText: string): Promise<number> {
  const t0 = Date.now();
  try {
    let input: HookInput;
    try {
      input = JSON.parse(stdinText || "{}") as HookInput;
    } catch {
      return 0;
    }
    const prompt = input.user_prompt ?? input.prompt ?? input.user_prompt_raw ?? "";
    if (!prompt.trim() || isSystemTraffic(prompt)) return 0;

    appendLog(
      {
        ts: new Date().toISOString(),
        session: input.session_id ?? "",
        prompt_hash: hashPrompt(prompt),
        domains: [],
        covered: [],
        discovered: [],
        installed: [],
        latency_ms: Date.now() - t0,
      },
      loadPolicy(),
    );
    return 0;
  } catch (err) {
    process.stderr.write(`[metaskill] route error: ${(err as Error).message}\n`);
    return 0;
  }
}
